### ISSUE TITLE
TypeError: node.highLevel is not a function

### ISSUE THREAD

**Issue by woodp** [raml-org/raml-js-parser-2#13]
I get this error when trying to parse this [API](https://github.com/raml-org/raml-dotnet-parser/blob/master/Raml.Parser.Tests/hybrid-api.raml):

```
C:\desarrollo\mulesoft\raml-dotnet-parser-raml1-bundle\Raml.Parser.Tester\bin\De
bug\node_modules\raml-1-0-parser\src\bundle.js:75
            return json2lowlevel.serialize(node.highLevel().lowLevel(), serializ
eOptions);
                                                ^
TypeError: node.highLevel is not a function
    at Object.toJSON (C:\desarrollo\mulesoft\raml-dotnet-parser-raml1-bundle\Ram
l.Parser.Tester\bin\Debug\node_modules\raml-1-0-parser\src\bundle.js:75:42)
    at Object.<anonymous> (C:\desarrollo\mulesoft\raml-dotnet-parser-raml1-bundl
e\Raml.Parser.Tester\bin\Debug\test.js:16:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by woodp** [comment]
This [API](https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/Raml.Tools.Tests/files/movies.raml) also issues the same error

**Comment by woodp** [comment]
There are errors on the API's (that went undetected with the previous js parser)

**Comment by sichvoge** [comment]
Cool @woodp - was about to look at that :)
