### ISSUE TITLE
Parser browser version fails in IE11

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#169]
`ReferenceError: 'Promise' is undefined`

IE11 does not support native Promises, so a polyfill must be used when building the parser browser version.

**Comment by juancoen** [comment]
Stacktrace:
```
ReferenceError: 'Promise' is undefined
   at processUnits (http://localhost:8081/api/console/scripts/api-console-vendor.js:10361:14)
   at Anonymous function (http://localhost:8081/api/console/scripts/api-console-vendor.js:10386:10)
   at processQueue (http://localhost:8081/api/console/scripts/api-console-vendor.js:422208:11)
   at Anonymous function (http://localhost:8081/api/console/scripts/api-console-vendor.js:422224:27)
   at Scope.prototype.$eval (http://localhost:8081/api/console/scripts/api-console-vendor.js:423460:9)
   at Scope.prototype.$digest (http://localhost:8081/api/console/scripts/api-console-vendor.js:423276:15)
   at Scope.prototype.$apply (http://localhost:8081/api/console/scripts/api-console-vendor.js:423565:13)
   at done (http://localhost:8081/api/console/scripts/api-console-vendor.js:418615:36)
   at completeRequest (http://localhost:8081/api/console/scripts/api-console-vendor.js:418805:7)
   at requestLoaded (http://localhost:8081/api/console/scripts/api-console-vendor.js:418746:9)
