### ISSUE TITLE
Uncaught TypeError: Cannot read property 'unit' of null

### ISSUE THREAD

**Issue by dreamflyer** [raml-org/raml-js-parser-2#467]
1) Create an empty file `types.raml`
2) Create a new RAML spec file with following content:
```RAML
#%RAML 1.0
title: spec
uses: 
```
Try to include an empty types library file. (`types: types.raml`)

### Result

IDE throws an error.

TypeError: Cannot read property 'unit' of null
TypeError: Cannot read property 'unit' of null
    at findDeclarations (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/ast.core/search.js:67:29)
    at /Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/ast.core/search.js:87:25
    at Array.forEach (native)
    at findDeclarations (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/ast.core/search.js:73:18)
    at Object.globalDeclarations (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/ast.core/search.js:36:28)
    at findTemplates (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/wrapped-ast/wrapperHelper.js:171:22)
    at Object.allTraits (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/wrapped-ast/wrapperHelper.js:147:12)
    at TraitsAndResourceTypesExpander.init (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/ast.core/expander.js:93:29)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/ast.core/expander.js:76:14)
    at Object.expandTraitsAndResourceTypes (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/ast.core/expander.js:27:10)
    at ASTNodeImpl.validate (/Users/vasil/Documents/api-workbench/testDevelop/raml-js-parser-2/dist/raml1/highLevelImpl.js:926:35)
    at gatherValidationErrors (/Users/vasil/Documents/api-workbench/testDevelop/api-workbench/src/atom/core/linter-ui.js:244:17)
    at actualLint (/Users/vasil/Documents/api-workbench/testDevelop/api-workbench/src/atom/core/linter-ui.js:150:5)
    at Object.lint (/Users/vasil/Documents/api-workbench/testDevelop/api-workbench/src/atom/core/linter-ui.js:71:18)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/vasil/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/vasil/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/vasil/.atom/packages/linter/lib/editor-linter.js:86:22
    at /Users/vasil/.atom/packages/linter/lib/helpers.coffee:25:18

**Comment by dreamflyer** [comment]
will be published in v1.1.3.
