### ISSUE TITLE
Unhandled Parsing Error

### ISSUE THREAD

**Issue by carlosmsr** [raml-org/raml-js-parser-2#496]
Given a format error like: 

  **type: datetime
        description: agent or device
	timestamp when the point was measured
        required: false**

the following line on [..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js (ln. 521)

**while (_issue.extras.length > 0)** 

generates this error message: 

TypeError: Cannot read property 'length' of undefined
    at Object.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:521:49)
    at ASTNodeImpl.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:939:16)
    at [..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:407:15
    at Array.forEach (native)
    at validateBasic ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:402:12)
    at Object.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\ast.core\linter.js:599:13)
    at ASTNodeImpl.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:939:16)
    at ASTNodeImpl.validate ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:932:24)
    at ASTNodeImpl.BasicASTNode.errors ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:157:14)
    at ApiImpl.BasicNodeImpl.errors ([..]\raml2html\node_modules\raml-1-parser\dist\raml1\wrapped-ast\parserCore.js:204:42)

Probably checking for:

**if(issue != null && issue.extras != null)**

would fix it.

**Comment by ddenisenko** [comment]
Can not reproduce, but still useful to add the  condition.

**Comment by carlosmsr** [comment]
I was produced by a syntax error on a multi line comment, like: 

property:
   type: theType 
   description: this multi line description
    had an enter that caused problems
  required: false

**Comment by dreamflyer** [comment]
will be published in v1.1.7.
