### ISSUE TITLE
Exception thrown when using libraries 

### ISSUE THREAD

**Issue by lijithv** [raml-org/raml-js-parser-2#553]
raml-1-parser version  -  1.1.8

Getting the following parsing error when using RAML 1.0 libraries
```
TypeError: Cannot create property 'name' on string 'type'
    at SimpleNamesTransformer.transform (/usr/local/lib/node_modules/raml2html/node_modules/raml-1-parser/dist/util/TCKDumper.js:839:19)
    at /usr/local/lib/node_modules/raml2html/node_modules/raml-1-parser/dist/util/TCKDumper.js:148:29
    at Array.forEach (native)
    at TCKDumper.dumpInternal (/usr/local/lib/node_modules/raml2html/node_modules/raml-1-parser/dist/util/TCKDumper.js:146:35)
    at TCKDumper.dump (/usr/local/lib/node_modules/raml2html/node_modules/raml-1-parser/dist/util/TCKDumper.js:99:27)
    at dump (/usr/local/lib/node_modules/raml2html/node_modules/raml-1-parser/dist/util/TCKDumper.js:24:8)
    at /usr/local/lib/node_modules/raml2html/node_modules/raml-1-parser/dist/util/TCKDumper.js:259:33
    at Array.forEach (native)
    at /usr/local/lib/node_modules/raml2html/node_modules/raml-1-parser/dist/util/TCKDumper.js:253:30
    at Array.forEach (native)
```
Attached below is the sample RAML project
[RAML_Sample.zip](https://github.com/raml-org/raml-js-parser-2/files/612513/RAML_Sample.zip)

**Comment by sichvoge** [comment]
I could reproduce it. Thanks for raising.

I already did some tests and it seems that the types are the problem. To remove the type definition itself from the list of possible problems, I manually including all the types and there isn't a problem with the type definition of a customer. My guess is that something goes wrong when processing `!include`s. 

We will look at this in more details!
