### ISSUE TITLE
Cannot read property 'absolutePath' of null

### ISSUE THREAD

**Issue by cascer1** [raml-org/raml-js-parser-2#559]
I cannot read any API spec using version 1.1.9 or 1.1.8.

The code I'm using is:

```
var raml= require('raml-js-parser');
var api = raml.loadApiSync(specPath);
```

I then get the following output:

```
C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\namespaceResolver.js:177
        var fromPath = unit.absolutePath();
                           ^

TypeError: Cannot read property 'absolutePath' of null
    at NamespaceResolver.nsMap (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\namespaceResolver.js:177:28)
    at ReferencePatcher.resolveReferenceValueBasic (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:363:38)
    at ReferencePatcher.resolveReferenceValue (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:329:29)
    at ReferencePatcher.patchType (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:264:44)
    at ReferencePatcher.patchReferences (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:81:18)
    at ReferencePatcher.patchReferences (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:88:18)
    at ReferencePatcher.process (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:35:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\expander.js:113:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\expander.js:91:27)
    at Object.expandTraitsAndResourceTypes (C:\Git\ramlapi\node_modules\raml-1-parser\dist\raml1\ast.core\expander.js:27:10)
```

**Comment by ddenisenko** [comment]
Could you please provide a RAML sample? Please attach all dependencies too.

**Comment by cascer1** [comment]
Excuse me for this, it seems some JSON schema I depended on was modified and a reference wasn't found.  This is not actually a bug and instead a user error.
