### ISSUE TITLE
Throws an error when "extensions and overlays" are undefined

### ISSUE THREAD

**Issue by blakeembrey** [raml-org/raml-js-parser-2#61]
```
	        throw new Error("Extensions and overlays list should be defined");
	        ^

Error: Extensions and overlays list should be defined
    at Object.loadApiAsync (/Users/blakeembrey/Projects/mulesoft-labs/raml-generator/node_modules/raml-1-parser/src/raml1Parser.js:27600:16)
    at Object.loadApi (/Users/blakeembrey/Projects/mulesoft-labs/raml-generator/node_modules/raml-1-parser/src/raml1Parser.js:4147:23)
    at Object.loadApi (/Users/blakeembrey/Projects/mulesoft-labs/raml-generator/node_modules/raml-1-parser/src/raml1Parser.js:54:25)
    at Object.bin (/Users/blakeembrey/Projects/mulesoft-labs/raml-generator/dist/bin.js:28:28)
    at Object.<anonymous> (/Users/blakeembrey/Projects/mulesoft-labs/raml-javascript-generator/dist/bin.js:4:7)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

The second argument is `undefined`.

**Comment by ddenisenko** [comment]
What were the loadApiAsync arguments?

**Comment by ddenisenko** [comment]
Hm. Just tested, all those variants of the call do not throw an error for a valid API:

```js
var parseResult = raml.loadApi(fName)
```

```js
var parseResult = raml.loadApi(fName, {
    rejectOnErrors : true
})
```

```js
var parseResult = raml.loadApi(fName, [fName2, fName3, fName4])
```

```js
var parseResult = raml.loadApi(fName, [fName2, fName3, fName4], {
    rejectOnErrors : true
})
```

**Comment by blakeembrey** [comment]
Undefined. `raml.loadApi(path, includes, { rejectOnErrors: true })` but `includes` is undefined. I just worked around it by saying `includes || []` but I'd expect `null` and `undefined` to be valid values - just as an empty array is.

**Comment by ddenisenko** [comment]
We supported a whole syntax of `raml.loadApi(path, { rejectOnErrors: true })` so that users do not have to put `undefined` as a second argument.

**Comment by petrochenko-pavel-a** [comment]
A actually agree with @blakeembrey.
pushed fix to RC2.

Regards,
Pavel
