### ISSUE TITLE
Exception: 'Cannot read property 'isOk' of undefined' when parsing the following RAML file.

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#646]
```
TypeError: Cannot read property 'isOk' of undefined
    at Status.addSubStatus (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:50:16)
    at /Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:1123:74
    at Array.forEach (native)
    at InheritedType.AbstractType.validateDirect (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:1123:37)
    at InheritedType.AbstractType.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:1166:34)
    at PropertyIs.MatchesProperty.validateProp (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/restrictions.js:55:20)
    at PropertyIs.check (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/restrictions.js:304:31)
    at /Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:1123:89
    at Array.forEach (native)
    at InheritedType.AbstractType.validateDirect (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:1123:37)
    at Example.validateValue (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/metainfo.js:287:37)
    at Example.validateSelf (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/metainfo.js:235:34)
    at /Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:762:15
    at Array.forEach (native)
    at InheritedType.AbstractType.validateMeta (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:761:29)
    at InheritedType.AbstractType.validateType (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-typesystem/dist/src/typesystem.js:621:18)
    at TypeDeclarationValidator.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:2245:34)
    at Object.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:750:44)
    at ASTNodeImpl.BasicASTNode.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1000:35)
    at /Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:580:15
    at Array.forEach (native)
    at validateBasic (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:574:12)
    at Object.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:778:13)
    at ASTNodeImpl.BasicASTNode.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1000:35)
    at ASTNodeImpl.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:993:24)
    at ASTNodeImpl.BasicASTNode.errors (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:170:14)
    at ApiImpl.BasicNodeImpl.errors (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:233:42)
    at loadRAMLInternal (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/apiLoader.js:76:46)
    at Object.loadApi (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/apiLoader.js:20:15)
    at Object.parseRAMLSync (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/index.js:60:22)
```

**Comment by glodieu** [comment]
[issue646.txt](https://github.com/raml-org/raml-js-parser-2/files/771503/issue646.txt)

**Comment by KonstantinSviridov** [comment]
Hi, @glodieu 

Thank you for the bug report!

The fix is available in the `develop` branches set and it will be brought to `master` with the following release -- 1.1.15. 

Regards, Konstantin
