### ISSUE TITLE
TypeError: Cannot read property 'isOk' of undefined

### ISSUE THREAD

**Issue by jayS-de** [raml-org/raml-js-parser-2#649]
The following RAML results in a TypeError.

example raml:
```raml
#%RAML 1.0
---
title: Test
types:
    Category:
        type: object
        properties:
            parent:
                type: CategoryReference
    Reference:
        type: object
        discriminator: typeId
        properties:
            typeId:
                type: string
            id:
                type: string
    CategoryReference:
        type: Reference
        discriminatorValue: category
mediaType: application/json
/category:
    get:
        description: Query category
        responses:
            200:
                body:
                    application/json:
                        example: { "parent": { "typeId": "category", "id": "12345" } }
                        type: Category

```

```
TypeError: Cannot read property 'isOk' of undefined
    at Status.addSubStatus (/workspace/raml/raml-typesystem/dist/src/typesystem.js:50:16)
    at /workspace/raml/raml-typesystem/dist/src/typesystem.js:1123:74
    at Array.forEach (native)
    at InheritedType.AbstractType.validateDirect (/workspace/raml/raml-typesystem/dist/src/typesystem.js:1123:37)
    at InheritedType.AbstractType.validate (/workspace/raml/raml-typesystem/dist/src/typesystem.js:1166:34)
    at PropertyIs.MatchesProperty.validateProp (/workspace/raml/raml-typesystem/dist/src/restrictions.js:55:20)
    at PropertyIs.check (//workspace/raml/raml-typesystem/dist/src/restrictions.js:304:31)
    at /workspace/raml/raml-typesystem/dist/src/typesystem.js:1123:89
    at Array.forEach (native)
    at InheritedType.AbstractType.validateDirect (/workspace/raml/raml-typesystem/dist/src/typesystem.js:1123:37)
```

I can workaround the issue by changing

```raml
types:
    Category:
        type: object
        properties:
            parent:
                type: CategoryReference
```

to 

```raml
types:
    Category:
        type: object
        properties:
            parent: CategoryReference
```

But as soon as there are more than only type information at a property this would not work anymore

The issue itself can be tracked down to in the raml-typesystem/src/metainfo.ts seems to be the issue as class DiscriminatorValue::check where the dVal will be null for the issue case resulting in no return value for the check function.

**Comment by KonstantinSviridov** [comment]
Hi, @jayS-de 

It's the same issue as https://github.com/raml-org/raml-js-parser-2/issues/646

Regards, Konstantin
