### ISSUE TITLE
this._originalNode.key is not a function error

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#668]
Using parser version 1.1.15, this error appears after parsing the following RAML:
```
TypeError: this._originalNode.key is not a function
    at LowLevelValueTransformingNode.LowLevelProxyNode.key (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/LowLevelASTProxy.js:75:35)
    at LowLevelValueTransformingNode.key (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/LowLevelASTProxy.js:641:40)
    at LowLevelCompositeNode.value (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/LowLevelASTProxy.js:260:27)
    at ASTPropImpl.calcValue (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:623:38)
    at ASTPropImpl.value (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:592:28)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:572:29)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.resetTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:568:18)
    at ReferencePatcher.process (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:46:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:115:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:98:27)
    at Object.expandTraitsAndResourceTypes (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:28:10)
    at ASTNodeImpl.validate (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1044:35)
    at ASTNodeImpl.BasicASTNode.errors (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:170:14)
    at loadRAMLInternalHL (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/apiLoader.js:136:46)
    at Object.loadApi (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/raml1/apiLoader.js:59:18)
    at Object.parseRAMLSync (/Users/gaston/mulesoft/oas-raml-converter/node_modules/raml-1-parser/dist/index.js:80:22)
    at e (/Users/gaston/mulesoft/oas-raml-converter/lib/importers/baseraml.js:653:31)
    at RAML10Importer.loadData (/Users/gaston/mulesoft/oas-raml-converter/lib/importers/baseraml.js:650:10)
    at Auto._parse (/Users/gaston/mulesoft/oas-raml-converter/lib/importers/auto.js:71:70)
    at Promise (/Users/gaston/mulesoft/oas-raml-converter/lib/importers/auto.js:41:19)
    at Auto.loadData (/Users/gaston/mulesoft/oas-raml-converter/lib/importers/auto.js:31:10)
    at err (/Users/gaston/mulesoft/oas-raml-converter/lib/exporters/exporter.js:38:15)
    at RAML10Exporter.export (/Users/gaston/mulesoft/oas-raml-converter/lib/exporters/exporter.js:27:10)
    at e (/Users/gaston/mulesoft/oas-raml-converter/lib/converter.js:54:29)
    at Converter.convert (/Users/gaston/mulesoft/oas-raml-converter/lib/converter.js:51:12)
    at loadFile.then (/Users/gaston/mulesoft/oas-raml-converter/lib/converter.js:23:14)
```

**Comment by sichvoge** [comment]
Can you attach the RAML please :)

**Comment by glodieu** [comment]
[raml.txt](https://github.com/raml-org/raml-js-parser-2/files/815005/raml.txt)

**Comment by glodieu** [comment]
Parsing fine using previous parser version.

**Comment by KonstantinSviridov** [comment]
Thanks for the report, @glodieu 

The fix is going to appear in the nearest hotfix patch, which is today or on Monday

Regards, Konstantin
