### ISSUE TITLE
Stacktrace attempting to pass parameter from child to parent resource type

### ISSUE THREAD

**Issue by erwinw** [raml-org/raml-js-parser-2#706]
When parsing below RAML using `raml1Parser.loadApiSync`, I'm getting a `TypeError: word.toLowerCase is not a function` exception.

The RAML:

```raml
#%RAML 1.0
title: Minimal bug case
types: { Category: string }
resourceTypes:
  parentResourceType:
    get:
      queryParameters:
        foo: <<typeName | !singularize>>
  childResourceType:
    type: { parentResourceType: { typeName: <<typeName>> } }

/cats:
  type:
    childResourceType: { typeName: category }
```

The stacktrace (paths trimmed to protect the innocent):
```
.../raml-parser/node_modules/pluralize/pluralize.js:134
      var token = word.toLowerCase();
                       ^

TypeError: word.toLowerCase is not a function
    at Function.plural (.../raml-parser/node_modules/pluralize/pluralize.js:134:24)
    at .../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:449:73
    at ValueTransformer.transform (.../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:584:35)
    at DefaultTransformer.transform (.../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:703:29)
    at ReferencePatcher.resolveReferenceValue (.../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:370:45)
    at ReferencePatcher.patchType (.../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:327:44)
    at ReferencePatcher.patchReferences (.../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:90:18)
    at ReferencePatcher.patchReferences (.../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:97:18)
    at ReferencePatcher.patchReferences (.../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:97:18)
    at ReferencePatcher.patchReferences (.../raml-parser/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:97:18)
```

So... basically, there's a child resource type (`childResourceType`) that is attempting to pass a parameter (`typeName`) through to the parent resource type (`parentResourceType`). If I remove the `{ typeName: <<typeName>> }` in the child resource type, I'm getting errors that the parameter isn't provided -- so it definitely needs to be here. However now I believe when attempting to singularize/pluralize, it's processing a reference to the parameter value rather than the value.

Am I doing it wrong (tm), or is this a bug?

Cheers,
Erwin

**Comment by KonstantinSviridov** [comment]
Thanks for the report, Erwin

The fix will be available in the next release.

Regards, Konstantin

**Comment by erwinw** [comment]
Great, thanks Konstantin!

Regards,
Erwin
