### ISSUE TITLE
Parser should return an error, not an exception

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#707]
For this RAML:

```yaml
#%RAML 1.0
title: test
baseUri: 
  name: api.example.com
```

The parser, v1.1.18, returns an exception not an error object.

```
TypeError: baseUri.indexOf is not a function
    at ProtocolsPropertyCalculator.calculate (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/defaultCalculator.js:346:35)
    at AttributeDefaultsCalculator.getAttributeDefault2 (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/defaultCalculator.js:94:40)
    at AttributeDefaultsCalculator.getAttributeDefault (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/defaultCalculator.js:68:25)
    at AttributeDefaultsCalculator.attributeDefaultIfEnabled (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/defaultCalculator.js:45:21)
    at ApiImpl.BasicNodeImpl.attributes (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:94:17)
    at ApiImpl.protocols (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/artifacts/raml10parser.js:5725:44)
    at /Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/util/TCKDumper.js:287:39
    at Array.forEach (native)
    at TCKDumper.dumpProperties (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/util/TCKDumper.js:274:28)
    at TCKDumper.dumpInternal (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/util/TCKDumper.js:120:28)
TypeError: baseUri.indexOf is not a function
    at ProtocolsPropertyCalculator.calculate (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/defaultCalculator.js:346:35)
    at AttributeDefaultsCalculator.getAttributeDefault2 (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/defaultCalculator.js:94:40)
    at AttributeDefaultsCalculator.getAttributeDefault (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/defaultCalculator.js:68:25)
    at AttributeDefaultsCalculator.attributeDefaultIfEnabled (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/defaultCalculator.js:45:21)
    at /Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:651:37
    at Array.forEach (native)
    at fillElementMeta (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:640:48)
    at ApiImpl.BasicNodeImpl.meta (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:312:16)
    at TCKDumper.serializeMeta (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/util/TCKDumper.js:493:25)
    at TCKDumper.dumpInternal (/Users/christianvogel/Projects/raml.github.org/raml-tck/examples/node/node_modules/raml-1-parser/dist/util/TCKDumper.js:138:18)
```

**Comment by ddenisenko** [comment]
How are you calling the parser (which methods in order)?

**Comment by sichvoge** [comment]
https://github.com/raml-org/raml-tck/blob/wip/2.0.0/examples/node/index.js#L118
