### ISSUE TITLE
Version 1.1.21: Error "ReferenceError: filePathMap is not defined" parsing raml file

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#734]
```
     ReferenceError: filePathMap is not defined
      at Object.content (test/lib/raml2oas.js:13:36)
      at Project.unit (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/jsyaml/jsyaml2lowLevel.ts:1071:37)
      at createIssue2 (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:4195:59)
      at NormalValidator.validate (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:1606:30)
      at CompositePropertyValidator.validate (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:1370:35)
      at Object.validate (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:765:42)
      at ASTPropImpl.BasicASTNode.validate (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/highLevelImpl.ts:235:16)
      at /Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:709:15
      at Array.forEach (native)
```

**Comment by glodieu** [comment]
Calling parser like this:
```

**Comment by glodieu** [comment]
Raml file:
```
#%RAML 0.8
title: title
version: 2.0

/:
  post:
    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/schema",
            "type": "object",
            "required": ["org_id", "api_id", "received_ts", "replied_ts", "verb", "status_code" ],
            "properties": {
              "org_id": { "type": "string" },
              "api_id": { "type": "string" },
              "api_version_id": { "type": "string" },
              "host_id": { "type": "string" },
              "client_id": { "type": "string" },
              "transaction_id": { "type": "string" },
              "received_ts": { "type": "iso datetime" },
              "replied_ts": { "type": "iso datetime" },
              "client_ip": { "type": "ip address"},
              "verb": { "type": "string" },
              "path": { "type": "string" },
              "status_code": { "type": "int" },
              "user_agent": { "type": "string" },
              "request_bytes": { "type": "long" },
              "response_bytes": { "type": "long" },
              "request_disposition": { "enum": ["PROCESSED", "BLOCKED"] },
              "policy_violation": {
                "type": "object",
                "oneOf": [{ "$ref": "#definitions/policy_violation" }]
              }
            },
            "definitions": {
              "policy_violation": {
                "type": "object",
                "properties": {
                  "policy_id": { "type": "string" },
                  "outcome": { "enum": ["VIOLATION", "ERROR"] }
                }
              }
            }
          }
```

**Comment by KonstantinSviridov** [comment]
Thanks for the bug report, @glodieu 

The fix is going to appear in the next release

Regards, Konstantin
