### ISSUE TITLE
Version 1.1.21: Error "TypeError: Cannot read property 'position' of null" parsing raml file.

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#735]
```
     TypeError: Cannot read property 'position' of null
      at localError (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:4025:28)
      at createIssue (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:4271:15)
      at createIssue1 (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:4210:12)
      at createIssue2 (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:4193:18)
      at ExampleAndDefaultValueValidator.parseObject (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:3627:39)
      at ExampleAndDefaultValueValidator.validate (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:3379:23)
      at CompositePropertyValidator.validate (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:1257:51)
      at Object.validate (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:765:42)
      at ASTPropImpl.BasicASTNode.validate (/Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/highLevelImpl.ts:235:16)
      at /Users/gaston.lodieu/github/mulesoft/oas-raml-converter/node_modules/raml-1-parser/src/raml1/ast.core/linter.ts:709:15
      at Array.forEach (native)
```

**Comment by glodieu** [comment]
```
const options = {
  "attributeDefaults": false,
  "rejectOnErrors": true,
  "validate": true,
  "noExtension": true,
  "format": "yaml"
}

const jsonOptions = {
  "serializeMetadata": false
}

parser.loadApi(filePath, options).expand(true).toJSON(jsonOptions)
```

**Comment by glodieu** [comment]
Raml file
```
#%RAML 0.8
title: Hello
version: V1

/v2: 
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/get-app-statistics.json
```

examples/get-app-statistics.json
```
{
  "1430867011087": 0,
  "1430903299087": 2,
  "1430915395087": 0,
}
```

**Comment by KonstantinSviridov** [comment]
Hi @glodieu 

The fix is going to appear in the next release.

Regards, Konstantin.

**Comment by jarrodek** [comment]
Was this fix released? For some reason I started having this error in a RAML file that was working before (from the Exchange - GitHub v3 RAML spec).

This is what I can see:

```
TypeError: Cannot read property 'position' of null
    at localError (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:3582:28)
    at createIssue (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:3794:17)
    at /Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:3170:92
    at Array.forEach (native)
    at Object.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:3170:52)
    at ExampleAndDefaultValueValidator.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:3005:20)
    at CompositePropertyValidator.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:1104:51)
    at Object.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:659:42)
    at ASTPropImpl.BasicASTNode.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:193:16)
    at /Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:601:15
    at Array.forEach (native)
    at validateBasic (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:595:12)
    at Object.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:802:13)
    at ASTNodeImpl.BasicASTNode.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1057:35)
    at /Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:601:15
    at Array.forEach (native)
    at validateBasic (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:595:12)
    at Object.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:802:13)
    at ASTNodeImpl.BasicASTNode.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1057:35)
    at /Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:601:15
    at Array.forEach (native)
    at validateBasic (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:595:12)
    at Object.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:802:13)
    at ASTNodeImpl.BasicASTNode.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1057:35)
    at /Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:601:15
    at Array.forEach (native)
    at validateBasic (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:595:12)
    at Object.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:802:13)
    at ASTNodeImpl.BasicASTNode.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1057:35)
    at /Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:601:15
    at Array.forEach (native)
    at validateBasic (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:595:12)
    at Object.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:802:13)
    at ASTNodeImpl.BasicASTNode.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1057:35)
    at ASTNodeImpl.BasicASTNode.errors (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:170:14)
    at errors (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:682:33)
    at ApiImpl.BasicNodeImpl.errors (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:246:16)
    at TCKDumper.dumpInternal (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/util/TCKDumper.js:178:59)
    at TCKDumper.dump (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/util/TCKDumper.js:101:27)
    at ApiImpl.BasicNodeImpl.toJSON (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:267:62)
at parser.loadApi.then.api (/Users/pawelpsztyc/workspace/api-console/node_modules/raml-json-enhance-node/lib/json-generator.js:75:8)
```

Where the `json-generator.js` around line 75 contains:

```
parse() {
    return parser.loadApi(someURL)
    .then(api => {
      return api.expand(true)
      .toJSON({
        dumpSchemaContents: false,
        rootNodeDetails: true,
        serializeMetadata: false
      });
    });
  }
```

**Comment by jarrodek** [comment]
This is happening when it is calling `.toJSON()`.
This is not happening for version `1.1.20`. Error is present in version `1.1.21` and `1.1.22`

**Comment by jarrodek** [comment]
The API is RAML 0.8

**Comment by ddenisenko** [comment]
1.1.22 is a patch release for a particular ticket. This fix will be released in 1.1.23.

**Comment by sichvoge** [comment]
So why is this closed?

And why did it work before in 1.1.20?

**Comment by ddenisenko** [comment]
>So why is this closed?

Because tickets are being closed when the fix is committed, not when it is released. Usually, it works well, but due to the unexpected 1.1.22 release there was some confusion.

**Comment by ddenisenko** [comment]
>And why did it work before in 1.1.20?

Because in 1.1.20 we were not adding JSON positioning inside the error reports. This particular exception happens when there is an error in JSON and it is located at the last character of JSON file.

**Comment by sichvoge** [comment]
So, @jarrodek most probably has an invalid RAML document?

**Comment by ddenisenko** [comment]
Invalid JSON, not RAML.
