### ISSUE TITLE
Simple RAML document fails to parse in unit test file

### ISSUE THREAD

**Issue by ijdickinson** [raml-org/raml-js-parser-2#751]
I'm trying to load a simple RAML document as a fixture in a unit test, but it's failing with an error message I don't understand. Here's my setup:

```javascript
import Raml from 'raml-1-parser-browser';

// const api = Raml.loadRAML('http://localhost:8080/static/api.raml');
const raml = `#%RAML 1.0
title: test-registry
baseUri: http://localhost:8080/test
/:
  get:
    displayName: List the register
    description: test fixture description
`;
const ramlDoc = Raml.parseRAMLSync(raml);
console.log(`parsed: ramlDoc is ${ramlDoc}`);
```

When I trying running this test in Karma, I get:

    PhantomJS 2.1.1 (Linux 0.0.0) ERROR
      TypeError: undefined is not an object (evaluating 'e.lowLevel')
      at webpack:///~/raml-1-parser-browser/index.js:32:0 <- index.js:20876
    PhantomJS 2.1.1 (Linux 0.0.0): Executed 0 of 0 ERROR (2.117 secs / 0 secs)

I have to use `raml-1-parser-browser` because (a) that's how I'm going to be running, and (b) Karma runs the tests in a PhantomJS browser. Unfortunately, that means that the source file location for the error isn't very helpful.

**Comment by ijdickinson** [comment]
Running that fragment with `raml-1-parser` from node, I get:

```
$ babel-node test.js
/home/ian/projects/registry-api-active-docs/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:186
    if (arg.lowLevel && arg.property) {
           ^

TypeError: Cannot read property 'lowLevel' of undefined
  at ApiImpl.BasicNodeImpl.toString (/home/ian/projects/registry-api-active-docs/node_modules/raml-1-parser/src/raml1/wrapped-ast/parserCore.ts:222:16)
  at Object.<anonymous> (/home/ian/projects/registry-api-active-docs/test.js:14:1)
  at Module._compile (module.js:570:32)
  at loader (/home/ian/.npm-packages/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
  at Object.require.extensions.(anonymous function) [as .js] (/home/ian/.npm-packages/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Function.Module.runMain (module.js:604:10)
  at Object.<anonymous> (/home/ian/.npm-packages/lib/node_modules/babel-cli/lib/_babel-node.js:154:22)
```

**Comment by KonstantinSviridov** [comment]
Hi, @ijdickinson 

In fact, loading passes fine in your case. The exception you see is thrown from `ramlDoc.toString()` (` ${ramlDoc}`). I suggest using `console.log(`parsed: ramlDoc is\n ${ramlDoc.toJSON()}`);` as `ApiImpl.toString()` is not supposed to be very informative.

Anyway, this case must be fixed, so thanks for reporting it.

Regards,
Konstantin

**Comment by ijdickinson** [comment]
Thanks @KonstantinSviridov!
