### ISSUE TITLE
problem with a reference patching process

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/raml-js-parser-2#758]
Hi I have following RAML:
```raml
#%RAML 1.0
title: Hello
mediaType: application/json
uses:
 views: views.raml
types:
  Method: any
  Class:
    type: object
    facets:
      methods?:
        properties:
          //: Method
  Repository:
    type: Class
    properties:
      id: integer
      name: string
      lastName: string
/hello/{id}:

  put:
    (views.views): [{id: x,fixedParameters: {a: hello} }]
    queryParameters:
       a?: string
    headers:
       b?: string
    body: Repository
    responses:
     200:
      body: Class
     400:
      body: string
```
which is using this library
```raml
#%RAML 1.0 Library
annotationTypes:
  id: string
  views:
     type: ResourceView | ResourceView[]

types:
  ResourceView:
     properties:
       id: string
       displayName?: string
       description?: string
       fixedParameters:
         properties:
           //: any
```
Unfortunately, when I am calling expand libraries, parser throws following error:
```
TypeError: x.isFromParentValue is not a function
    at node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:20:67
    at Function.findIndex (node_modules\raml-1-parser\node_modules\underscore\underscore.js:620:13)
    at Function._.find._.detect (node_modules\raml-1-parser\node_modules\underscore\underscore.js:214:15)
    at new KeyMatcher (node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:20:30)
    at BasicNodeBuilder.process (node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:185:22)
    at node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:153:60
    at Array.forEach (native)
    at BasicNodeBuilder.process (node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:145:28)
    at ASTNodeImpl.children (node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:1562:42)
    at ASTNodeImpl.attrs (node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:1726:23)
    at ReferencePatcher.patchReferenceAttr (node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:181:46)
    at ReferencePatcher.patchReferences (node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:100:18)
    at ReferencePatcher.patchReferences (node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:100:18)
    at ReferencePatcher.process (node_modules\raml-1-parser\dist\raml1\ast.core\referencePatcher.js:37:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (node_modules\raml-1-parser\dist\raml1\ast.core\expander.js:119:16)
    at LibraryExpander.expandLibraries (node_modules\raml-1-parser\dist\raml1\ast.core\expander.js:473:31)
    at Object.expandLibraries (node_modules\raml-1-parser\dist\raml1\ast.core\expander.js:33:34)
    at expandLibraries (node_modules\raml-1-parser\dist\raml1\wrapped-ast\wrapperHelper.js:107:16)
    at Object.expandSpec (node_modules\raml-1-parser\dist\raml1\wrapped-ast\wrapperHelper.js:82:16)
    at ApiImpl.expand (node_modules\raml-1-parser\dist\raml1\artifacts\raml10parser.js:5872:23)
```
Thanks in advance,
Pavel

**Comment by KonstantinSviridov** [comment]
Hi, Pavel

The fix is going to be available in the next release
