### ISSUE TITLE
Getting npm err while i do npm install for package.json attached

### ISSUE THREAD

**Issue by VinayKadalagi** [raml-org/raml-js-parser-2#836]
Please I need help. I am not getting which dependency in my package.json is using a repository `https://github.com/isaacloud/raml-js-parser.git` which does not exist.
Here is full [npm log](https://bitbucket.org/vinaykad/atlassian-ui-challenge/src/test/logs/2019-02-09T21_01_03_878Z-debug.log) 
Here is [package.json](https://bitbucket.org/vinaykad/atlassian-ui-challenge/src/test/package.json) i am using
I get below error when i try to npm install with above package.json

```
verbose stack Error: exited with error code: 128
15487 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
15487 verbose stack     at ChildProcess.emit (events.js:197:13)
15487 verbose stack     at maybeClose (internal/child_process.js:978:16)
15487 verbose stack     at Socket.stream.socket.on (internal/child_process.js:395:11)
15487 verbose stack     at Socket.emit (events.js:197:13)
15487 verbose stack     at Pipe._handle.close (net.js:611:12)
15488 verbose cwd /Users/i348081/Documents/bitbucket/atlassian-ui-challenge
15489 verbose Darwin 18.0.0
15490 verbose argv "/usr/local/Cellar/node/11.9.0/bin/node" "/usr/local/bin/npm" "install"
15491 verbose node v11.9.0
15492 verbose npm  v6.5.0
15493 error Error while executing:
15493 error /usr/bin/git ls-remote -h -t https://github.com/isaacloud/raml-js-parser.git
15493 error
15493 error ERROR: Repository not found.
15493 error fatal: Could not read from remote repository.
15493 error
15493 error Please make sure you have the correct access rights
15493 error and the repository exists.
15493 error
15493 error exited with error code: 128
15494 verbose exit [ 1, true ]

```

**Comment by jstoiko** [comment]
getting access denied on you links

**Comment by postatum** [comment]
Closing for now as no answers. Feel free to provide more information and re-open if this is still relevant.
